### PR TITLE
Add support for Invoke Release

### PR DESCRIPTION
**Pull request by eb-enzo**

### CODE REVIEW

**Comment by nickwilliams-eventbrite** [comment]
Is Tikibar open source? If no, shouldn't we be using Phabricator? If yes, we either should not be using Invoke Release, or we should make a plan for open-sourcing Invoke Release.

**Comment by ebpitts** [comment]
@nickwilliams-eventbrite tikibar repo is public, but parts of it are too tied to our customizations of Django for anyone outside Eventbrite to use. https://github.com/eventbrite/tikibar/issues?q=is%3Aissue+is%3Aopen+label%3A%22Open+Sourcing%22 tracks issues related to fixing that.

I don't have strong opinions either way, but I lean towards saying its okay to use invoke-release even within code we've open-sourced, since only Eventbrite employees will be making releases.

Agreed that we should talk about opne-sourcing invoke-release, too.

**Comment by nickwilliams-eventbrite** [comment]
`CHANGELOG.txt` must have at least the following in it:

```
Changelog
==========

0.0.16 (2017-07-07)
-------------------
- Initial release
```

But consider adding more versions to that.

`HISTORY.rst` can be deleted.

`tikibar/__init__.py` should `from tikibar.version import __version__, __version_info__  # noqa`.

**Comment by eb-enzo** [comment]
I'm doing a new pull request, sorry, just closed this without reading the comments.

**Pull request closed without merging**
